from .base_model_form import BaseModelForm
from .formulario_agregar_material_mayor import FormularioAgregarMaterialMayor
from .formulario_editar_material_mayor import FormularioEditarMaterialMayor
from .formulario_adquisicion_material_mayor import FormularioAdquisicionMaterialMayor
from .formulario_adquisicion_compra_material_mayor import FormularioAdquisicionCompraMaterialMayor
from .formulario_adquisicion_donacion_material_mayor import FormularioAdquisicionDonacionMaterialMayor
from .material_mayor_search_form import MaterialMayorSearchForm
from .formulario_asignacion_cuerpo_material_mayor import FormularioAsignacionCuerpoMaterialMayor
from .formulario_asignacion_compania_material_mayor import FormularioAsignacionCompaniaMaterialMayor
from .formulario_hoja_vida_asignacion_cuerpo_material_mayor import FormularioHojaVidaAsignacionCuerpoMaterialMayor
from .formulario_hoja_vida_asignacion_compania_material_mayor import FormularioHojaVidaAsignacionCompaniaMaterialMayor
from .formulario_asignacion_patente_material_mayor import FormularioAsignacionPatenteMaterialMayor
from .formulario_hoja_vida_asignacion_patente_material_mayor import FormularioHojaVidaAsignacionPatenteMaterialMayor
from .formulario_agregar_pauta_mantencion_carrosado import FormularioAgregarPautaMantencionCarrosado
from .formulario_agregar_pauta_mantencion_chasis import FormularioAgregarPautaMantencionChasis
from .formulario_cambio_pauta_mantencion_carrosado_material_mayor import FormularioCambioPautaMantencionCarrosadoMaterialMayor
from .formulario_hoja_vida_cambio_pauta_mantencion_carrosado_material_mayor import FormularioHojaVidaCambioPautaMantencionCarrosadoMaterialMayor
from .formulario_cambio_numero_chasis_material_mayor import FormularioCambioNumeroChasisMaterialMayor
from .formulario_hoja_vida_cambio_numero_chasis_material_mayor import FormularioHojaVidaCambioNumeroChasisMaterialMayor
from .formulario_cambio_numero_motor_material_mayor import FormularioCambioNumeroMotorMaterialMayor
from .formulario_hoja_vida_cambio_numero_motor_material_mayor import FormularioHojaVidaCambioNumeroMotorMaterialMayor
from .formulario_hoja_vida_asignacion_compania_material_mayor import FormularioHojaVidaAsignacionCompaniaMaterialMayor
from formulario_pauta_mantencion_carrosado_agregar import FormularioPautaMantencionCarrosadoAgregar
from formulario_pauta_mantencion_chasis_agregar import FormularioPautaMantencionChasisAgregar
from .formulario_cambio_certificado_anotaciones_vigentes import FormularioCambioCertificadoAnotacionesVigentes
from .formulario_hoja_vida_cambio_certificado_anotaciones_vigentes import FormularioHojaVidaCambioCertificadoAnotacionesVigentes
from .formulario_asignacion_solicitud_primera_inscripcion import FormularioAsignacionSolicitudPrimeraInscripcion
from .formulario_hoja_vida_asignacion_solicitud_primera_inscripcion import FormularioHojaVidaAsignacionSolicitudPrimeraInscripcion

__all__ = [ 'BaseModelForm',
			'FormularioAgregarMaterialMayor',
			'FormularioEditarMaterialMayor',
			'FormularioAdquisicionMaterialMayor',
			'FormularioAdquisicionCompraMaterialMayor',
			'FormularioAdquisicionDonacionMaterialMayor',
			'MaterialMayorSearchForm',
			'FormularioAsignacionCuerpoMaterialMayor',
			'FormularioHojaVidaAsignacionCuerpoMaterialMayor',
			'FormularioAsignacionCompaniaMaterialMayor',
			'FormularioHojaVidaAsignacionCompaniaMaterialMayor',
			'FormularioAsignacionPatenteMaterialMayor',
			'FormularioHojaVidaAsignacionPatenteMaterialMayor',
			'FormularioAgregarPautaMantencionCarrosado',
			'FormularioAgregarPautaMantencionChasis',
			'FormularioCambioPautaMantencionCarrosadoMaterialMayor',
			'FormularioHojaVidaCambioPautaMantencionCarrosadoMaterialMayor',
			'FormularioCambioNumeroChasisMaterialMayor',
			'FormularioHojaVidaCambioNumeroChasisMaterialMayor',
			'FormularioCambioNumeroMotorMaterialMayor',
			'FormularioHojaVidaCambioNumeroMotorMaterialMayor',
			'FormularioHojaVidaAsignacionCompaniaMaterialMayor',
			'FormularioPautaMantencionCarrosadoAgregar',
			'FormularioPautaMantencionChasisAgregar',
            'FormularioCambioCertificadoAnotacionesVigentes',
            'FormularioHojaVidaCambioCertificadoAnotacionesVigentes',
            'FormularioAsignacionSolicitudPrimeraInscripcion',
            'FormularioHojaVidaAsignacionSolicitudPrimeraInscripcion']
