from .base_model_form import BaseModelForm
from .formulario_dar_de_alta_material_mayor import FormularioDarDeAltaMaterialMayor
from .formulario_adquisicion_material_mayor import FormularioAdquisicionMaterialMayor
from .formulario_adquisicion_compra_material_mayor import FormularioAdquisicionCompraMaterialMayor
from .formulario_adquisicion_donacion_material_mayor import FormularioAdquisicionDonacionMaterialMayor
from .material_mayor_search_form import MaterialMayorSearchForm
from .formulario_asignacion_cuerpo_material_mayor import FormularioAsignacionCuerpoMaterialMayor
from .formulario_hoja_vida_asignacion_cuerpo_material_mayor import FormularioHojaVidaAsignacionCuerpoMaterialMayor


__all__ = [ 'BaseModelForm',
			'FormularioDarDeAltaMaterialMayor',
			'FormularioAdquisicionMaterialMayor',
			'FormularioAdquisicionCompraMaterialMayor',
			'FormularioAdquisicionDonacionMaterialMayor',
			'MaterialMayorSearchForm',
			'FormularioAsignacionCuerpoMaterialMayor',
			'FormularioHojaVidaAsignacionCuerpoMaterialMayor']
