from models import *
from django.contrib import admin

admin.site.register(TipoVehiculoMaterialMayor)
admin.site.register(MarcaChasisMaterialMayor)
admin.site.register(ModeloChasisMaterialMayor)
admin.site.register(MarcaCarrosadoMaterialMayor)
admin.site.register(MarcaCajaCambioMaterialMayor)
admin.site.register(ModeloCajaCambioMaterialMayor)
admin.site.register(ColorMaterialMayor)
admin.site.register(CondicionMaterialMayor)
admin.site.register(MaterialMayor)
admin.site.register(TipoCombustibleMaterialMayor)
admin.site.register(TipoCajaCambioMaterialMayor)
admin.site.register(MarcaBombaMaterialMayor)
admin.site.register(ModeloBombaMaterialMayor)
admin.site.register(Pais)
admin.site.register(AdquisicionMaterialMayor)
admin.site.register(AdquisicionCompraMaterialMayor)
admin.site.register(AdquisicionDonacionMaterialMayor)
admin.site.register(ModoAdquisicionMaterialMayor)
admin.site.register(Region)
admin.site.register(Provincia)
admin.site.register(Comuna)
admin.site.register(Cuerpo)
admin.site.register(Compania)
admin.site.register(EventoHojaVidaMaterialMayor)
admin.site.register(TipoEventoHojaVidaMaterialMayor)
admin.site.register(AsignacionCuerpoMaterialMayor)
admin.site.register(UserProfile)
admin.site.register(Rol)
admin.site.register(Cargo)
admin.site.register(FamiliaUsoMaterialMayor)
admin.site.register(UsoMaterialMayor)
