# coding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('interface.views',
    url(r'^$', 'index', name='index'),
    url(r'^logout/$', 'logout', name='logout'),
    (r'^pauta_mantencion/carrosado/$', 'pauta_mantencion_carrosado'),
    (r'^pauta_mantencion/carrosado/(?P<pauta_mantencion_carrosado_id>\d+)/$', 'pauta_mantencion_carrosado_editar'),
    (r'^pauta_mantencion/carrosado/(?P<pauta_mantencion_carrosado_id>\d+)/eliminar/$', 'pauta_mantencion_carrosado_eliminar'),
    (r'^pauta_mantencion/carrosado/agregar/$', 'agregar_pauta_mantencion_carrosado'),
    (r'^pauta_mantencion/chasis/$', 'pauta_mantencion_chasis'),
    (r'^pauta_mantencion/chasis/(?P<pauta_mantencion_chasis_id>\d+)/$', 'pauta_mantencion_chasis_editar'),
    (r'^pauta_mantencion/chasis/(?P<pauta_mantencion_chasis_id>\d+)/eliminar/$', 'pauta_mantencion_chasis_eliminar'),
    (r'^pauta_mantencion/chasis/agregar/$', 'agregar_pauta_mantencion_chasis'),
    (r'^modelos_chasis/$', 'modelos_chasis'),
    (r'^modelos_chasis/(?P<modelo_chasis_id>\d+)/cambiar_pauta/$', 'cambiar_pauta_modelo_chasis'),
    (r'^material_mayor/$', 'material_mayor'),
    (r'^material_mayor.xls$', 'material_mayor_excel'),
    (r'^material_mayor/dar_de_alta/compra/$', 'adquisicion_compra_material_mayor'),
    (r'^material_mayor/dar_de_alta/donacion/$', 'adquisicion_donacion_material_mayor'),
    (r'^material_mayor/sin_validar/$', 'material_mayor_sin_validar'),
    (r'^material_mayor/sin_validar.xls$', 'material_mayor_sin_validar_excel'),
    (r'^material_mayor/(?P<material_mayor>\d+)/$', 'editar_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/cambiar_pauta_mantencion_carrosado/$', 'cambiar_pauta_mantencion_carrosado'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/$', 'mantenciones_programadas'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+)/$', 'detalle_mantencion_programada'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+).xls$', 'detalle_mantencion_programada_excel'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+)/operaciones/(?P<operacion_mantencion_id>\d+)/marcar_como_ejecutada/$', 'marcar_operacion_mantencion_programada_como_ejecutada'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+)/operaciones/(?P<operacion_mantencion_id>\d+)/marcar_como_pospuesta/$', 'marcar_operacion_mantencion_programada_como_pospuesta'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+)/archivos/agregar/$', 'agregar_archivo_mantencion_programada'),
    (r'material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_programada_id>\d+)/archivos/(?P<archivo_id>\d+)/eliminar/$', 'eliminar_archivo_mantencion_programada'),
    (r'material_mayor/(?P<material_mayor>\d+)/cambiar_certificado_anotaciones_vigentes/$', 'cambiar_certificado_anotaciones_vigentes'),
    (r'material_mayor/(?P<material_mayor>\d+)/asignar_solicitud_primera_inscripcion/$', 'asignar_solicitud_primera_inscripcion'),
    (r'material_mayor/(?P<material_mayor>\d+)/validar/$', 'validar_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/cambiar_numero_chasis/$', 'cambiar_numero_chasis_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/cambiar_numero_motor/$', 'cambiar_numero_motor_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/dar_de_baja/$', 'dar_de_baja_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/eliminar/$', 'eliminar_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/adquisicion/$', 'editar_adquisicion_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/asignar_a_cuerpo/$', 'asignar_material_mayor_a_cuerpo'),
    (r'material_mayor/(?P<material_mayor>\d+)/asignar_a_compania/$', 'asignar_material_mayor_a_compania'),
    (r'material_mayor/(?P<material_mayor>\d+)/asignar_patente/$', 'asignar_patente_a_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/detalles_patente/$', 'detalles_patente_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/hoja_de_vida/$', 'detalles_hoja_de_vida_material_mayor'),
    (r'material_mayor/(?P<material_mayor>\d+)/hoja_de_vida/(?P<evento_id>\d+)/$', 'detalle_evento_hoja_de_vida_material_mayor'),
    (r'^mantenciones_programadas/pendientes/$', 'mantenciones_programadas_pendientes'),
)

urlpatterns += patterns('interface.views_media',
    (r'media/documentos/material_mayor/(?P<material_mayor>\d+)/(?P<field_name>\w+)\.(?P<extension>\w+)$','descargar_documento_material_mayor'),
    (r'media/fotografias/material_mayor/(?P<material_mayor>\d+)/(?P<field_name>\w+)\.(?P<extension>\w+)$','descargar_fotografia_material_mayor'),
    (r'media/documentos/material_mayor/(?P<material_mayor>\d+)/adquisicion/(?P<field_name>\w+)\.(?P<extension>\w+)$','descargar_documento_adquisicion_material_mayor'),
    (r'media/documentos/material_mayor/(?P<material_mayor>\d+)/evento_hoja_vida/(?P<evento_id>\d+)-(?P<field_name>\w+)\.(?P<extension>\w+)$','descargar_documento_evento_material_mayor'),
    (r'media/documentos/material_mayor/(?P<material_mayor>\d+)/mantenciones_programadas/(?P<mantencion_id>\d+)/(?P<archivo_id>\d+)\.(?P<extension>\w+)$','descargar_documento_mantencion_programada_material_mayor'),
)

urlpatterns += patterns('interface.views_services',
    (r'^services/part_model_list/$', 'part_model_list'),
)
